FacilityFeedback.RazorPage/Pages/AccountPage/Create.cshtml.cs
using FacilityFeedback.Data.Models;
using FacilityFeedback.Service.IServices;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FacilityFeedback.RazorPage.Pages.AccountPage
{
    public class CreateModel : PageModel
    {
        private readonly IAccountService _service;

        public CreateModel(IAccountService service)
        {
            _service = service;
        }

        public async Task<IActionResult> OnGet()
        {
            return Page();
        }

        [BindProperty]
        public Account Account { get; set; } = default!;


        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid || Account == null)
            {
                return Page();
            }

            Account.Password = "123";
            Account.Role = "STAFF";
            var result = await _service.Create(Account);

            return RedirectToPage("./Index");
        }
    }
}

FacilityFeedback.RazorPage/Pages/AccountPage/Delete.cshtml.cs
using FacilityFeedback.Data.Models;
using FacilityFeedback.Service.IServices;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FacilityFeedback.RazorPage.Pages.AccountPage
{
    public class DeleteModel : PageModel
    {
        private readonly IAccountService _service;

        public DeleteModel(IAccountService service)
        {
            _service = service;
        }

        public async Task<IActionResult> OnGet(string email)
        {
            var account = await _service.GetByEmail(email);
            if (account == null)
            {
                return NotFound();
            }
            else
            {
                Account = account;
            }
            return Page();
        }

        [BindProperty]
        public Account Account { get; set; } = default!;


        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync(string email)
        {
            await _service.Delete(email);

            return RedirectToPage("./Index");
        }
    }
}

FacilityFeedback.RazorPage/Pages/AccountPage/Details.cshtml.cs
using FacilityFeedback.Data.Models;
using FacilityFeedback.Service.IServices;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FacilityFeedback.RazorPage.Pages.AccountPage
{
    public class DetailsModel : PageModel
    {
        private readonly IAccountService _service;

        public DetailsModel(IAccountService service)
        {
            _service = service;
        }

        public Account Account { get; set; } = default!; 

        public async Task<IActionResult> OnGetAsync(string email)
        {
            var account = await _service.GetByEmail(email);
            if (account == null)
            {
                return NotFound();
            }
            else
            {
                Account = account;
            }
            return Page();
        }
    }
}

FacilityFeedback.RazorPage/Pages/AccountPage/Edit.cshtml.cs
using FacilityFeedback.Data.Models;
using FacilityFeedback.Service.IServices;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FacilityFeedback.RazorPage.Pages.AccountPage
{
    public class EditModel : PageModel
    {
        private readonly IAccountService _service;

        public EditModel(IAccountService service)
        {
            _service = service;
        }

        public async Task<IActionResult> OnGet(string email)
        {
            var device = await _service.GetByEmail(email);
            if (device == null)
            {
                return NotFound();
            }
            else
            {
                Account = device;
            }
            return Page();
        }

        [BindProperty]
        public Account Account { get; set; } = default!;


        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid || Account == null)
            {
                return Page();
            }
            var result = await _service.Update(Account);

            return RedirectToPage("./Index");
        }
    }
}

FacilityFeedback.RazorPage/Pages/DevicePage/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using FacilityFeedback.Data.Models;
using FacilityFeedback.Service.IServices;

namespace FacilityFeedback.RazorPage.Pages.DevicePage
{
    public class CreateModel : PageModel
    {
        private readonly IDeviceService _service;
        private readonly IDeviceTypeService _deviceTypeService;
        private readonly IRoomService _roomService;

        public CreateModel(IDeviceService service, IDeviceTypeService deviceTypeService, IRoomService roomService)
        {
            _service = service;
            _deviceTypeService = deviceTypeService;
            _roomService = roomService;
        }

        public async Task<IActionResult> OnGet()
        {
            ViewData["DeviceTypeId"] = new SelectList(await _deviceTypeService.GetAllNoPaging(), "Id", "Name");
            ViewData["RoomId"] = new SelectList(await _roomService.GetAllNoPaging(), "Id", "RoomCode");
            return Page();
        }

        [BindProperty]
        public Device Device { get; set; } = default!;


        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid || Device == null)
            {
                return Page();
            }
            var result = await _service.Create(Device);

            return RedirectToPage("./Index");
        }
    }
}

FacilityFeedback.RazorPage/Pages/DevicePage/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using FacilityFeedback.Data.Models;
using FacilityFeedback.Service.IServices;

namespace FacilityFeedback.RazorPage.Pages.DevicePage
{
    public class DeleteModel : PageModel
    {
        private readonly IDeviceService _service;
        private readonly IDeviceTypeService _deviceTypeService;
        private readonly IRoomService _roomService;
        private readonly IProblemService _problemService;

        public DeleteModel(IDeviceService service, IDeviceTypeService deviceTypeService, IRoomService roomService,IProblemService problemService)
        {
            _service = service;
            _deviceTypeService = deviceTypeService;
            _roomService = roomService;
            _problemService = problemService;
        }

        public async Task<IActionResult> OnGet(int id)
        {
            var device = await _service.GetById(id);
            if (device == null)
            {
                return NotFound();
            }
            else
            {
                device.DeviceType = await _deviceTypeService.GetById(device.DeviceTypeId);
                device.Room = await _roomService.GetById(device.RoomId);
                Device = device;
            }
            return Page();
        }

        [BindProperty]
        public Device Device { get; set; } = default!;


        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync(int id)
        {
            var problems = await _problemService.GetAllNoPaging();
            var isExsitedProblem = false;
            if(problems != null)
            {
                isExsitedProblem =  problems.Where(x=>x.DeviceId == id).Any();
            }
            if (!isExsitedProblem)
            {
                await _service.Delete(id);
            }
            else
            {
                var updateDevice = problems?.Where(x => x.DeviceId == id).Select(x => x.Device).FirstOrDefault();
                updateDevice.Status = false;
                await _service.Update(updateDevice);
            }

            return RedirectToPage("./Index");
        }
    }
}

FacilityFeedback.RazorPage/Pages/DevicePage/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using FacilityFeedback.Data.Models;
using FacilityFeedback.Service.IServices;

namespace FacilityFeedback.RazorPage.Pages.DevicePage
{
    public class DetailsModel : PageModel
    {
        private readonly IDeviceService _service;
        private readonly IDeviceTypeService _deviceTypeService;
        private readonly IRoomService _roomService;

        public DetailsModel(IDeviceService service, IDeviceTypeService deviceTypeService, IRoomService roomService)
        {
            _service = service;
            _deviceTypeService = deviceTypeService;
            _roomService = roomService;
        }

        public Device Device { get; set; } = default!; 

        public async Task<IActionResult> OnGetAsync(int id)
        {
            var device = await _service.GetById(id);
            if (device == null)
            {
                return NotFound();
            }
            else
            {
                device.DeviceType = await _deviceTypeService.GetById(device.DeviceTypeId);
                device.Room = await _roomService.GetById(device.RoomId);
                Device = device;
            }
            return Page();
        }
    }
}

FacilityFeedback.RazorPage/Pages/DevicePage/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FacilityFeedback.Data.Models;
using FacilityFeedback.Service.IServices;

namespace FacilityFeedback.RazorPage.Pages.DevicePage
{
    public class EditModel : PageModel
    {
        private readonly IDeviceService _service;
        private readonly IDeviceTypeService _deviceTypeService;
        private readonly IRoomService _roomService;

        public EditModel(IDeviceService service, IDeviceTypeService deviceTypeService, IRoomService roomService)
        {
            _service = service;
            _deviceTypeService = deviceTypeService;
            _roomService = roomService;
        }

        public async Task<IActionResult> OnGet(int id)
        {
            var device = await _service.GetById(id);
            if (device == null)
            {
                return NotFound();
            }
            else
            {
                ViewData["DeviceTypeId"] = new SelectList(await _deviceTypeService.GetAllNoPaging(), "Id", "Name");
                ViewData["RoomId"] = new SelectList(await _roomService.GetAllNoPaging(), "Id", "RoomCode");
                Device = device;
            }
            return Page();
        }

        [BindProperty]
        public Device Device { get; set; } = default!;


        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid || Device == null)
            {
                return Page();
            }
            var result = await _service.Update(Device);

            return RedirectToPage("./Index");
        }
    }
}

FacilityFeedback.RazorPage/Pages/DeviceTypePage/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using FacilityFeedback.Data.Models;
using FacilityFeedback.Service.IServices;

namespace FacilityFeedback.RazorPage.Pages.DeviceTypePage
{
    public class CreateModel : PageModel
    {
        private readonly IDeviceTypeService _service;

        public CreateModel(IDeviceTypeService service)
        {
            _service = service;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public DeviceType DeviceType { get; set; } = default!;


        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid || DeviceType == null)
            {
                return Page();
            }
            var result = await _service.Create(DeviceType);

            return RedirectToPage("./Index");
        }
    }
}

FacilityFeedback.RazorPage/Pages/DeviceTypePage/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using FacilityFeedback.Data.Models;

namespace FacilityFeedback.RazorPage.Pages.DeviceTypePage
{
    public class DeleteModel : PageModel
    {
        private readonly FacilityFeedback.Data.Models.FacilityFeedbackContext _context;

        public DeleteModel(FacilityFeedback.Data.Models.FacilityFeedbackContext context)
        {
            _context = context;
        }

        [BindProperty]
      public DeviceType DeviceType { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.DeviceType == null)
            {
                return NotFound();
            }

            var devicetype = await _context.DeviceType.FirstOrDefaultAsync(m => m.Id == id);

            if (devicetype == null)
            {
                return NotFound();
            }
            else 
            {
                DeviceType = devicetype;
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null || _context.DeviceType == null)
            {
                return NotFound();
            }
            var devicetype = await _context.DeviceType.FindAsync(id);

            if (devicetype != null)
            {
                DeviceType = devicetype;
                if (_context.Device.Where(x => x.DeviceTypeId == id).Any())
                {
                    DeviceType.Status = false;
                    _context.DeviceType.Update(DeviceType);
                }
                else
                {
                    _context.DeviceType.Remove(DeviceType);
                }
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

FacilityFeedback.RazorPage/ViewComponents/TaskProcessStateViewComponent.cs
using FacilityFeedback.Data.Models;
using FacilityFeedback.RazorPage.Pages;
using FacilityFeedback.Service.IServices;
using FacilityFeedback.Service.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using System.Drawing.Printing;
using System.Linq;
using X.PagedList;

namespace FacilityFeedback.RazorPage.ViewComponents
{
    public class TaskProcessStateViewComponent : ViewComponent
    {
        private readonly ITaskProcessService _service;
        private readonly IAccountService _accountService;
        private readonly IConfiguration _config;
        public TaskProcessStateViewComponent(ITaskProcessService service, IConfiguration config, IAccountService accountService)
        {
            _service = service;
            _config = config;
            _accountService = accountService;
        }
        public async Task<IViewComponentResult> InvokeAsync(string state, int pageIndex)
        {
            var userString = HttpContext.Session.GetString("ACCOUNT");
            var userConvert = JsonConvert.DeserializeObject<Account>(userString);
            var isShowAll = true;
            if (userConvert.Role == "STAFF")
            {
                isShowAll = false;
            }
            
            var account = await _accountService.GetAllNoPaging();
            var sl2 = new SelectList(account.Where(a => a.Role == "STAFF"), "Email", "Email");
            ViewData["Account"] = sl2;

            var pageSize = Int32.Parse(_config["BaseConfig:PageSize"] ?? "10");
            pageIndex = pageIndex < 1 ? 1 : pageIndex;
            var TaskProcess = await _service.GetAllNoPaging();
            var TaskProcessPaging = await TaskProcess.Where(tp => (tp.Process.ToString() == state) 
                                    && (isShowAll || (tp.StaffEmail == userConvert.Email 
                                    || (tp.Process == Data.EnumModels.ProcessStatus.Incoming && tp.StaffEmail == null))))
                                    .ToPagedListAsync(pageIndex, 5);
            ViewBag.state = state;
            return View(TaskProcessPaging);
        }

    }
}

FacilityFeedback.RazorPage/Pages/TaskProcessPage/Create.cshtml
@page
@model FacilityFeedback.RazorPage.Pages.TaskProcessPage.CreateModel

@{
    ViewData["Title"] = "Create";
    var problemSelectList = (SelectList)ViewBag.ProblemId;
}

<div class="container-fluid pt-4 px-4">
    <div class="row g-4">
        <div class="col-sm-12 col-xl-7">
            <div class="bg-light rounded h-100 p-4">
                <h6 class="mb-4">Add Task Process</h6>
                <form method="post">
                    <div class="row mb-3">
                        @Html.ValidationSummary(false, "", new { @class = "text-danger" })

                        @Html.LabelFor(m => m.TaskProcess.StartTime, new {@class = "col-sm-2 col-form-label"})
                        <div class="col-sm-10">
                            @Html.EditorFor(m => m.TaskProcess.StartTime, new {@class = "form-control"})
                        </div>
                    </div>

                    <div class="row mb-3">
                        @Html.LabelFor(m => m.TaskProcess.EndTime, new {@class = "col-sm-2 col-form-label"})
                        <div class="col-sm-10">
                            @Html.EditorFor(m => m.TaskProcess.EndTime, new {@class = "form-control"})
                        </div>
                    </div>
                    <div class="row mb-3">
                        @Html.LabelFor(m => m.TaskProcess.Description, new {@class = "col-sm-2 col-form-label"})
                        <div class="col-sm-10">
                            @Html.TextBoxFor(m => m.TaskProcess.Description, new {@class = "form-control"})
                        </div>
                    </div>
                    <div class="row">
                        @Html.LabelFor(m => m.TaskProcess.Problem, new {@class = "col-sm-2 col-form-label"})
                        <div class="col-sm-10">
                            @Html.DropDownListFor(m => m.TaskProcess.ProblemId, problemSelectList, new {@class="form-select mb-3"})
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary">Create</button>
                </form>

                <div style="margin-top: 20px;">
                    <a asp-page="Index">Back to List</a>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

FacilityFeedback.RazorPage/Pages/TaskProcessPage/Delete.cshtml
@page
@model FacilityFeedback.RazorPage.Pages.TaskProcessPage.DeleteModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>TaskProcess</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TaskProcess.StartTime)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TaskProcess.StartTime)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TaskProcess.EndTime)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TaskProcess.EndTime)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TaskProcess.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TaskProcess.Description)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TaskProcess.Process)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TaskProcess.Process)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TaskProcess.Problem)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TaskProcess.Problem.Description)
        </dd>
    </dl>
    
    <form method="post">
        <input type="hidden" asp-for="TaskProcess.Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-page="./Index">Back to List</a>
    </form>
</div>

FacilityFeedback.RazorPage/Pages/TaskProcessPage/Details.cshtml
@page
@model FacilityFeedback.RazorPage.Pages.TaskProcessPage.DetailsModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>TaskProcess</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TaskProcess.StartTime)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TaskProcess.StartTime)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TaskProcess.EndTime)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TaskProcess.EndTime)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TaskProcess.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TaskProcess.Description)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TaskProcess.Process)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TaskProcess.Process)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TaskProcess.Problem)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TaskProcess.Problem.Description)
        </dd>
    </dl>
</div>
<div>
    <a asp-page="./Edit" asp-route-id="@Model.TaskProcess?.Id">Edit</a> |
    <a asp-page="./Index">Back to List</a>
</div>

FacilityFeedback.RazorPage/Pages/TaskProcessPage/Edit.cshtml
@page
@using FacilityFeedback.Data.EnumModels;
@model FacilityFeedback.RazorPage.Pages.TaskProcessPage.EditModel

@{
    ViewData["Title"] = "Edit";
    var problemSelectList = (SelectList)ViewBag.ProblemId;
}

<div class="container-fluid pt-4 px-4">
    <div class="row g-4">
        <div class="col-sm-12 col-xl-7">
            <div class="bg-light rounded h-100 p-4">
                <h6 class="mb-4">Edit Task Management</h6>
                <form method="post">
                    <div class="row mb-3">
                        @Html.ValidationSummary(false, "", new { @class = "text-danger" })
                        @Html.TextBoxFor(m => m.TaskProcess.Id, new {@hidden = "true"})

                        @Html.LabelFor(m => m.TaskProcess.StartTime, new {@class = "col-sm-2 col-form-label"})
                        <div class="col-sm-10">
                            @Html.EditorFor(m => m.TaskProcess.StartTime, new {@class = "form-control"})
                        </div>
                    </div>

                    <div class="row mb-3">
                        @Html.LabelFor(m => m.TaskProcess.EndTime, new {@class = "col-sm-2 col-form-label"})
                        <div class="col-sm-10">
                            @Html.EditorFor(m => m.TaskProcess.EndTime, new {@class = "form-control"})
                        </div>
                    </div>
                    <div class="row mb-3">
                        @Html.LabelFor(m => m.TaskProcess.Description, new {@class = "col-sm-2 col-form-label"})
                        <div class="col-sm-10">
                            @Html.TextBoxFor(m => m.TaskProcess.Description, new {@class = "form-control"})
                        </div>
                    </div>
                    <div class="row">
                        @Html.LabelFor(m => m.TaskProcess.Problem, new {@class = "col-sm-2 col-form-label"})
                        <div class="col-sm-10">
                            @Html.DropDownListFor(m => m.TaskProcess.ProblemId, problemSelectList, new {@class="form-select mb-3"})
                        </div>
                    </div>
                    <div class="row">
                        <input type="hidden" id="currentProcess" value="@Model.TaskProcess.Process" disabled="disabled"/>
                        @Html.LabelFor(m => m.TaskProcess.Process, new {@class = "col-sm-2 col-form-label"})
                        <div class="col-sm-10">
                            @*   @Html.EnumDropDownListFor(m => m.TaskProcess.Process, new {@class="form-select mb-3"}) *@
                            <select asp-for="TaskProcess.Process" class="form-select mb-3" 
                             asp-items="Html.GetEnumSelectList<ProcessStatus>()">
                            </select>
                        </div>
                    </div>


                    <button type="submit" class="btn btn-primary">Edit</button>
                </form>

                <div style="margin-top: 20px;">
                    <a asp-page="Index">Back to List</a>
                </div>
            </div>
        </div>
    </div>
</div>


@section Scripts {
    @{
        <script src="../js/TaskProcess/TaskProcessPageEdit.js"></script>
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

FacilityFeedback.RazorPage/Pages/TaskProcessPage/Index.cshtml
@page
@using X.PagedList.Mvc.Core;
@using X.PagedList.Web.Common;
@using FacilityFeedback.Data.ViewModels;
@model FacilityFeedback.RazorPage.Pages.TaskProcessPage.IndexModel
@Html.AntiForgeryToken();
@{
    ViewData["Title"] = "Index";
}

<h1>Task management</h1>

<p>
    <a asp-page="Create">Create New</a>
</p>

<div style="min-height: 350px">
    <h2>Waiting State</h2>
    <div id="WaitingState">
        @await Component.InvokeAsync("TaskProcessState", new {state = "Waiting", pageIndex = 1})
    </div>
</div>

<div style="min-height: 350px">
    <h2>Incoming State</h2>
    <div id="IncomingState">
        @await Component.InvokeAsync("TaskProcessState", new {state = "Incoming", pageIndex = 1})
    </div>
</div>

<div style="min-height: 350px">
    <h2>Processing State</h2>
    <div id="ProcessingState">
        @await Component.InvokeAsync("TaskProcessState", new {state = "Processing", pageIndex = 1})
    </div>
</div>

<div style="min-height: 350px">
    <h2>Finishing State</h2>
    <div id="FinishingState">
        @await Component.InvokeAsync("TaskProcessState", new {state = "Finishing", pageIndex = 1})
    </div>
</div>

<div style="min-height: 350px">
    <h2>Ending State</h2>
    <div id="EndingState">
        @await Component.InvokeAsync("TaskProcessState", new {state = "Ending", pageIndex = 1})
    </div>
</div>
@section Scripts {
    <script src="../js/TaskProcess/TaskProcessIndex.js"></script>
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}